version: '3'
services:
  web:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./lib:/app/lib
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./blogs:/app/blogs
      - ./events:/app/events
      - ./content:/app/content
      - ./layout:/app/layout
      - ./models:/app/models
